network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s3:
      dhcp4: false
      addresses: [192.168.00.00/24]
      gateway4: 192.168.00.1
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]
